# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpellBeeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='Question number', unique=True)),
                ('word', models.CharField(help_text='The word.', max_length=70, unique=True)),
                ('phonetics', models.CharField(help_text='Phonetics for the word.', max_length=80)),
                ('audio', models.FileField(help_text='Audio pronunciation for the word.', upload_to='')),
            ],
        ),
    ]
