# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spellbeequestion',
            options={'verbose_name': 'spell bee question', 'verbose_name_plural': 'spell bee questions'},
        ),
        migrations.AlterField(
            model_name='spellbeequestion',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio pronunciation for the word.', null=True, upload_to=''),
        ),
    ]
