# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0003_auto_20170522_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellbeequestion',
            name='meaning',
            field=models.TextField(help_text='Meaning of the word.', max_length=100),
        ),
        migrations.AlterField(
            model_name='spellbeequestion',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin of word. latin etc.', max_length=70, null=True),
        ),
    ]
