# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0005_auto_20170522_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Quiz title e.g Math Storm!, Let's go Quantum!, The Hardest Quiz Ever!!!! etc.", max_length=50)),
                ('description', models.CharField(blank=True, help_text="Quiz description e.g 'A math quiz based on elementary school mathematics.'", max_length=200, null=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the quiz.', upload_to='')),
                ('increment_per_question', models.IntegerField(default=4, help_text='The increment to be made in the score per right answer.')),
                ('negative_score', models.IntegerField(default=-1, help_text="The decrement to be made in the score per wrong answer (Include the minus '-' sign).")),
            ],
        ),
    ]
