# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0006_quizinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellbeequestion',
            name='word',
            field=models.CharField(help_text='The word.', max_length=20, unique=True),
        ),
    ]
