# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0008_auto_20170524_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinfo',
            name='timer',
            field=models.IntegerField(default=0, help_text='Time limit per question. Set 0 to disable timer.'),
        ),
    ]
