# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0009_quizinfo_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spellbeequestion',
            name='phonetics',
        ),
        migrations.AddField(
            model_name='spellbeequestion',
            name='usage',
            field=models.CharField(blank=True, help_text='A sentence using the given word.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spellbeequestion',
            name='origin',
            field=models.CharField(blank=True, default='', help_text='Origin of word. latin etc.', max_length=70, null=True),
        ),
    ]
