# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0021_auto_20170613_0953'),
        ('spell_bee', '0010_auto_20170605_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellBeeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spell_bee.QuizInfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Team')),
            ],
        ),
    ]
