# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell_bee', '0011_spellbeescore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spellbeescore',
            options={'verbose_name': 'Spell Bee Score', 'verbose_name_plural': 'spell Bee Scores'},
        ),
    ]
