# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category name e.g Logical reasoning, Maths etc.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the right option?')),
                ('content', models.CharField(help_text='The option.', max_length=70)),
            ],
            options={
                'verbose_name_plural': 'options',
                'verbose_name': 'option',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='The question.', max_length=500)),
                ('explanation', models.CharField(blank=True, help_text='An explanation to display after showing the correct answer to the question.', max_length=500, null=True)),
                ('image_asset', models.ImageField(blank=True, help_text='An image asset related to the question', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'questions',
                'verbose_name': 'question',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Quiz title e.g Math Storm!, Let's go Quantum!, The Hardest Quiz Ever!!!! etc.", max_length=50)),
                ('description', models.CharField(blank=True, help_text="Quiz description e.g 'A math quiz based on elementary school mathematics.'", max_length=200, null=True)),
                ('random_order', models.BooleanField(default=True, help_text='Display the questions in a randomized order instead of following the sequence as is.')),
                ('max_questions', models.IntegerField(default=15, help_text='Maximum number of questions to be displayed in a single quiz sitting')),
                ('increment_per_question', models.IntegerField(default=4, help_text='The increment to be made in the score per right answer.')),
                ('negative_score', models.IntegerField(default=-1, help_text="The decrement to be made in the score per wrong answer (Include the minus '-' sign).")),
                ('timer', models.IntegerField(default=0, help_text='Time limit per question. Set 0 to disable timer.')),
                ('success_message', models.CharField(default='Well done!', help_text='A success message to be displayed when the right answer is selected.', max_length=70)),
                ('fail_message', models.CharField(default='Uh-Oh!', help_text='The message to be displayed if the user fails to answer correctly.', max_length=70)),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not the quiz should be accessible.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Category')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'verbose_name': 'quiz',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz this question belongs to.', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(help_text='The question this option belongs to.', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Question'),
        ),
    ]
