# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text='Team description', max_length=700),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
