# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20170509_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutassets',
            name='quiz_chooser_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
