# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_layoutassets_quiz_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutassets',
            name='quiz_background',
        ),
    ]
