# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_remove_layoutassets_quiz_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for the quiz.', upload_to=''),
        ),
    ]
