# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_quiz_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_asset',
            field=models.FileField(blank=True, help_text='Audio asset for the given question.', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1, help_text='Question number (relative to current quiz).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='video_asset',
            field=models.FileField(blank=True, help_text='Video asset for this question', null=True, upload_to=''),
        ),
    ]
