# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 03:34
# Generated by Django 1.11 on 2017-05-16 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_auto_20170515_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Team')),
            ],
        ),
    ]
