# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_auto_20170516_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score_record',
            field=models.CharField(blank=True, help_text='A score record of the team progress. DO NOT MESS WITH THIS!', max_length=1000, null=True),
        ),
    ]
