# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_team_score_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutassets',
            name='score_board_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
