# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0015_layoutassets_score_board_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutassets',
            name='homepage_background_image',
        ),
        migrations.AddField(
            model_name='layoutassets',
            name='homepage_intro_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
