# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_auto_20170518_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutassets',
            name='team_intro_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
