# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0018_auto_20170523_1211'),
    ]

    operations = [
    ]
