# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0021_auto_20170613_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='The question.', max_length=500, unique=True),
        ),
    ]
