# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0022_auto_20170614_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='increment_per_question',
            field=models.IntegerField(default=5, help_text='The increment to be made in the score per right answer.'),
        ),
    ]
