# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_fire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapidfirequestion',
            options={'verbose_name': 'Rapid Fire Question', 'verbose_name_plural': 'Rapid Fire Questions'},
        ),
        migrations.AlterModelOptions(
            name='rapidfirequiz',
            options={'verbose_name': 'Rapid Fire Quiz', 'verbose_name_plural': 'Rapid Fire Quiz'},
        ),
        migrations.AlterModelOptions(
            name='rapidfirescore',
            options={'verbose_name': 'Rapid Fire Score', 'verbose_name_plural': 'Rapid Fire Scores'},
        ),
        migrations.RemoveField(
            model_name='rapidfirequiz',
            name='max_questions',
        ),
        migrations.RemoveField(
            model_name='rapidfirequiz',
            name='team',
        ),
        migrations.AddField(
            model_name='rapidfirequiz',
            name='questions_per_team',
            field=models.IntegerField(default=15, help_text='Number of questions to be displayed per team'),
        ),
    ]
