# -*- coding: utf-8 -*-

# Generated by Django 1.11 on 2017-06-24 05:46

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_fire', '0004_auto_20170614_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapidfirequestion',
            name='answer',
            field=models.CharField(default='', help_text='Correct answer to the question', max_length=100),
            preserve_default=False,
        ),
    ]
